### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by samcov** [kjpou1/Mono.Wasm.Samples#1]
Where is the assembly that "using WebAssembly" is defined in?

Missing a Nuget?

**Comment by kjpou1** [comment]
We do not have nuget files yet.  The WebAssembly files can be found in the downloaded mono wasm package:  https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/obtain-wasm-sdk.md

You can generate the project by following the doc here:  https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/sample.md

**Comment by kjpou1** [comment]
Added build instructions.

**Comment by samcov** [comment]
Thanks Kenneth, I'll utilize this as soon as I get some time.
